### ISSUE TITLE
clojure -M:serve fails because could not find shadow/cljs/devtools/cli

### ISSUE THREAD

**Issue by vladkotu** [fulcro-community/fulcro-exercises#4]
Hi there.
Thanx for sharing fulcro exercises.
 
I'v tried to run an app as follow:
```
npm install
clojure -M:serve
```
and got this exception:
```
Execution error (FileNotFoundException) at clojure.main/main (main.java:40).
Could not locate shadow/cljs/devtools/cli__init.class, shadow/cljs/devtools/cli.clj or shadow/cljs/devtools/cli.cljc on classpath.
```

**Comment by holyjak** [comment]
Sorry for not responding early, I have not have notification for the repo configured correctly.

What version of Clojure CLI do you have? I have

```
❯  clojure --version 
CLI version 1.10.3.855
```

and that works fine on my PC.

Clojure CLI is developed heavily and sometimes you need a compatible version for deps.edn to do what you expect.
